export enum OrderActions {
  SET_STEP_INC = "SETSTEPINC",
  SET_STEP_DEC = "SETSTEPDEC",
  SET_SIZE = "SETSIZE",
  SET_BBQ = "SETBBQ",
  SET_SPEAKER = "SETSPEAKER",
  SET_CHAIRS = "SETCHAIRS",
  SET_TABLES = "SETTABLES",
  SET_DATE = "SETDATE",
  SET_ADDRESS = "SETADDRESS",
  SET_USER = "SETUSER",
}
